    [build-system]
    requires = ["setuptools>=64"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "nsw-tas-fuel-api-client"
    version = "0.0.2"
    readme = "README.md"
    description = "Client library for NSW Fuel API"
    authors = [
        { name = "bicycleboy", email = "bicycleboy61@gmail.com" },
        { name = "Nick Whyte", email = "nick@nickwhyte.com" },
    ]
    license =  "MIT"
    requires-python = ">=3.14"
    dependencies = [
        "aiohttp>=3.14",
        "rich>=10.1.0,<11.0.0",
    ]

    classifiers = [
        "Intended Audience :: Developers",
        "Programming Language :: Python",
    ]

    [project.urls]
    Homepage = "https://github.com/bicycleboy/nsw-tas-fuel-api-client"
    Release-Notes = "https://github.com/bicycleboy/nsw-tas-fuel-api-client/releases"

    [project.optional-dependencies]
    test = [
        "pytest",
        "pytest-asyncio",
        "pytest-cov",
        "requests-mock",
        "aiointercept",
        "dotenv",
        "ruff",
        "twine",
    ]

    [tool.setuptools.packages.find]
    where = ["."]
    include = ["nsw_tas_fuel"]

    [tool.pytest.ini_options]
    # Automatically discover tests inside these paths
    testpaths = ["tests"]


    # Markers for async tests, integration, etc.
    markers = [
        "asyncio: mark test as async",
        "integration: mark test as integration-level"
    ]

    # Use a verbose output and colored diff for readability
    addopts = "-v --tb=short --color=yes"

    [tool.pylint.design]
    max-args = 6

[tool.ruff]
required-version = ">=0.16.9"
target-version = "py314"

[tool.ruff.lint.per-file-ignores]
"getprices.py" = [
    "ASYNC230",
    "BLE001",
]
"demo.py" = [
    "ASYNC230",
    "BLE001",
]
"tests/*.py" = [
    "ASYNC230",
    "BLE001",
    "DTZ001",
]
