#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
source .venv/bin/activate
python -m ensurepip --upgrade
python -m pip install --upgrade pip
python3 -m pip install '.[test]'
echo 'source .venv/bin/activate' > ~/.bashrc